name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}
      
      - uses: actions/checkout@v2
      
      - run: npm install
      - run: npm run cy:run
      - run: npm run report:merge
      - run: npm run report:mocha
      
      - name: Deploy to GithubPages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: $${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: machawesome-report
